### ISSUE TITLE
Proxy server credentials not accepted

### ISSUE THREAD

**Issue by bertva** [warrieka/geopunt4Qgis#11]
In our organization we work with a proxy server.
When filled in in"settings" they work fine for the "OpenLayers" plugin, but when using the geopunt4qgis. plugin, we get a warning 

message : "Warning: Proxy Authentication Required".

![capture](https://cloud.githubusercontent.com/assets/23724549/20604047/b7e2507a-b264-11e6-9a87-77b829c603b8.PNG)

**Comment by mstuyts** [comment]
I get some errors that are probably related. We use a proxy server to connect, but in the QGIS settings we use "DefaultProxy" as Proxy type, so it uses the Windows Proxy settings.

When I select "Geopunt-catalogus" I get the following error.
![geopunt4qgis_error1](https://user-images.githubusercontent.com/11028014/29774996-d42d4df6-8c03-11e7-8927-05f021b44d91.JPG)

When I search for something, I get a different error.
![geopunt4qgis_error2](https://user-images.githubusercontent.com/11028014/29774997-d42dea22-8c03-11e7-998d-0e91902e9148.JPG)
When I copy-paste the url from the error message to my browser it works just fine.

The plugin "quick_map_services" can connect to the internet so it probably has nothing to do with my QGIS settings.

**Comment by warrieka** [comment]
My plugin uses al lot of tailored AGIV-webservices, quick_map_services only adds a bunch of layers that can be parsed directly by QGIS and added as  xyz-layers, so QGIS-settings are used automatic. I need to read these settings and pass them to python-urllib to access these services.  Right now I only can read the proxy-settings if entered explicitly. 

Any way the AGIV server has been out a few times, but hese issues should be resolved, this might also be a reason for your problom,

**Comment by mstuyts** [comment]
In quick_map_services you can download a contributed pack of layers, that probably needs the proxy settings too.  It manages to get the "DefaultProxy" settings with the following script: https://github.com/nextgis/quickmapservices/blob/master/src/qgis_settings.py

I still get the same error and as said before, if I copy-paste the url from the error to my web browser, the service works just fine. so it probably isn't because of the services being down.

**Comment by warrieka** [comment]
should be fixed in qgis3 version
